"""added db relations 2

Revision ID: 16e8e2976ede
Revises: def7f3fad11b
Create Date: 2021-12-26 02:09:19.277262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16e8e2976ede'
down_revision = 'def7f3fad11b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('department_uuid', sa.String(), nullable=True))
    op.drop_constraint('employee_department_id_fkey', 'employee', type_='foreignkey')
    op.create_foreign_key(None, 'employee', 'department', ['department_uuid'], ['uuid'])
    op.drop_column('employee', 'department_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.create_foreign_key('employee_department_id_fkey', 'employee', 'department', ['department_id'], ['id'])
    op.drop_column('employee', 'department_uuid')
    # ### end Alembic commands ###
