"""Updated db relations

Revision ID: 3ad3816ee5e2
Revises: ead1af4779ed
Create Date: 2021-12-26 18:36:36.236738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ad3816ee5e2'
down_revision = 'ead1af4779ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('department_id', sa.Integer(), nullable=True))
    op.drop_constraint('employee_department_uuid_fkey', 'employee', type_='foreignkey')
    op.create_foreign_key(None, 'employee', 'department', ['department_id'], ['id'])
    op.drop_column('employee', 'department_uuid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('department_uuid', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.create_foreign_key('employee_department_uuid_fkey', 'employee', 'department', ['department_uuid'], ['uuid'])
    op.drop_column('employee', 'department_id')
    # ### end Alembic commands ###
