"""Added uuid

Revision ID: af47d023df1a
Revises: 2e0079fe67ba
Create Date: 2021-12-11 23:37:27.804011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af47d023df1a'
down_revision = '2e0079fe67ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column('uuid', sa.String(length=36), nullable=True))
    op.create_unique_constraint(None, 'department', ['uuid'])
    op.add_column('employee', sa.Column('uuid', sa.String(length=36), nullable=True))
    op.create_unique_constraint(None, 'employee', ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee', type_='unique')
    op.drop_column('employee', 'uuid')
    op.drop_constraint(None, 'department', type_='unique')
    op.drop_column('department', 'uuid')
    # ### end Alembic commands ###
